### PR TITLE
Document how to check for redirects and handle them

### PR DESCRIPTION
**Pull request by zbarnes757**
Connected to #190 

This is my first time adding documentation for something so please please please be free with feedback 😄 

Are there any other topics you would like me to add to this PR?

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @zbarnes757, thanks a lot for your work! A few high-level notes:

  1. We probably want this in a documentation page called "Handling redirects" instead of "Common issues" since I think it justifies a topic by itself.

  1. Let's be a bit more detailed in how we handle redirects and go into more detail specifically on different use cases, such as cases where you want to close the original connection or cases where you want to keep the new connection open after the request.

  1. Let's have a bit more context around the example, such as a module.

Great job!!

**Comment by lucaspiller** [comment]
I would add a note on the location url possibly being a relative rather than absolute url. Unfortunately it's not as simple as just looking for the right header :)

Here is the equivalent function I'm using, I'm using [fuzzyurl](https://github.com/gamache/fuzzyurl.ex) for URL manipulation:

```elixir
  defp can_redirect(original_url, headers) do
    downcase_headers = for {k, v} <- headers, into: %{}, do: {String.downcase(k), v}

    case Map.get(downcase_headers, "location") do
      # Location is missing from headers
      nil ->
        false

      <<"http://", _::binary>> = url ->
        {true, url}

      # Absolute URL, https
      <<"https://", _::binary>> = url ->
        {true, url}

      # Relative URL
      relative_url ->
        try do
          original_fu = Fuzzyurl.from_string(original_url)
          relative_fu = Fuzzyurl.from_string(relative_url)

          # Mix and match
          url =
            original_fu
            |> Map.put(:path, relative_fu.path)
            |> Map.put(:query, relative_fu.query)
            |> Fuzzyurl.to_string()

          {true, url}
        rescue
          # Fuzzyurl will throw an error if it can't parse the URL
          error in ArgumentError ->
            Logger.warn(
              "Error extracting relative url original=#{original_url} relative=#{relative_url} error=#{
                inspect(error)
              }"
            )

            {:error, error}
        end
    end
  end
```

**Comment by at88mph** [comment]
Thanks for the sample code @lucaspiller.  I have a specific use case that drove the original issue for this.

To put the function you posted to use, would I use the URL returned, if there is one, to start a new `Mint.HTTP.connect()` with that URL and close the previous one?

Thanks.

**Comment by ericmj** [comment]
> To put the function you posted to use, would I use the URL returned, if there is one, to start a new Mint.HTTP.connect() with that URL and close the previous one?

Only if the URL is for another host, if it's the same host we can reuse the connection.

**Comment by ericmj** [comment]
Closing this due to lack of activity.

**Pull request closed without merging**
