### PR TITLE
Add OTP 23 to CI

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by ericmj** [comment]
We have an ssl failure on OTP 23.

@voltone Do you know what is causing it?

**Comment by voltone** [comment]
I suspect it is due to https://github.com/erlang/otp/commit/db8d19bbfb53d3c3c40ce6067f05710108b47f9d. Still don't understand exactly why and whether it's an OTP bug or some side effect of Mint's shims that we'll have to work around...

**Comment by voltone** [comment]
Yes, confirmed:

On recent OTP versions you should set `customize_hostname_check: [match_fun: :public_key.pkix_verify_hostname_match_fun(:https)` to ensure wildcard certs with SAN extension are handled correctly. This assumes the hostname check is done by OTP's `verify_fun`.

In Mint we use a custom `verify_fun`, to backport some certificate chain verification fixes and make sure everything works properly on older OTP versions. Until the PR mentioned above, setting `verify_fun` meant you had to do hostname verification yourself, so that's what Mint does.

The PR changes that: now OTP will try to verify the hostname before calling the custom `verify_fun` hook for the end-certificate. Since we don't pass the `customize_hostname_check` function (since Mint assumes it can do its own), the verification of wildcard certs fails.

A workaround might be to add `customize_hostname_check: [match_fun: &match_fun/2]` to `Mint.Core.Transport.SSL.default_ssl_opts/1`: that will work on recent OTP versions. It will do duplicate hostname verification on OTP, so perhaps the call to `:mint_shims.pkix_verify_hostname/3` in `verify_fun/3` should be conditional on the OTP version. The main question is whether this workaround will break older OTP versions. I have no easy way to test that right now...

**Comment by ericmj** [comment]
Included in https://github.com/elixir-mint/mint/pull/261.

**Pull request closed without merging**
